# Generated by Django 6.0.2 on 2026-02-05 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otp_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='is_used',
        ),
    ]
