# Generated by Django 6.0.2 on 2026-02-06 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_otp_is_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='user',
            new_name='otps',
        ),
    ]
