# Generated by Django 6.0.2 on 2026-02-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_user_otp_otps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='type',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('reset', 'reset')], null=True),
        ),
    ]
